OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: ""

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "source/Inap-NADPH探针 20210702 chm Tao 2017.pdf"
  file_format: "markdown"